language: bash
services: docker
env:
  - VERSION=3.2
  - VERSION=3.4
before_script:
- env | sort
- cd "$VERSION"
- image="mongodb-tools:$VERSION"
script:
- travis_retry docker build -t "$image" .
after_script:
- docker images
